import React, { useState, useEffect } from "react"
import type { NextPage } from "next"
import Head from "next/head"
import axios from "axios"
import Navbar from "../components/Navbar"
import Loader from "../components/Loader"
import Link from "next/link"
import style from "../styles/pages/Home.module.css"
import ProductList from "../components/ProductList"

const Home: NextPage = () => {
    const [products, setProducts] = useState([])

    const getProducts = async () => {
        const response = await axios.get("/api/products")
        const results = response.data
        setProducts(results)
    }

    useEffect(() => {
        getProducts()
    }, [])

    return (
        <React.Fragment>
            <Head>
                <title>Next CRUD</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />
            {!products.length ? (
                <Loader />
            ) : (
                <ul style={{ textAlign: "center", marginTop: "1opx" }}>
                    {products.map(({ name, price }, index) => (
                        <ProductList key={index} name={name} price={price} />
                    ))}
                </ul>
            )}

            <div className={style.buttonWrapper}>
                <Link href="/products/add">
                    <h1 className={style.button}>Add</h1>
                </Link>
            </div>
        </React.Fragment>
    )
}

export default Home
