import type { NextPage } from "next"
import Head from "next/head"
import React from "react"

const Home: NextPage = () => {
    return (
        <React.Fragment>
            <Head>
                <title>Next CRUD</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1>Next Crud</h1>
        </React.Fragment>
    )
}

export default Home
